version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_teacher_search
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: teacher_search
      MYSQL_USER: zakaraya
      MYSQL_PASSWORD: zeroonetwothree
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_teacher_search
    environment:
      PMA_HOST: mysql_teacher_search
      PMA_USER: zakaraya
      PMA_PASSWORD: zeroonetwothree
    ports:
      - "8081:80"
    depends_on:
      - mysql_teacher_search

volumes:
  mysql_data:
